[[constraint]]
  branch = "master"
  name = "github.com/badoux/checkmail"

[[constraint]]
  branch = "master"
  name = "github.com/skratchdot/open-golang"

[[constraint]]
  branch = "master"
  name = "github.com/mitchellh/go-homedir"

[[constraint]]
  version = "1.0.0"
  name = "github.com/yookoala/realpath"

[[constraint]]
  name = "github.com/mholt/archiver"
  version = "2.0.0"

[prune]
  go-tests = true
  unused-packages = true
